<a href="https://colab.research.google.com/github/shamim34/code_practice/blob/master/icu_patient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


In [0]:
import os

In [5]:
!pip install "tensorflow>=1.15,<2.0"

In [0]:
import os
os.chdir('drive/My Drive/Colab Notebooks/')

In [0]:
data_directory = 'data/'
data = []
for file in os.listdir(data_directory):
    if(str(file).split('.')[1] == 'csv'):
        reader = pd.read_csv(os.path.join(data_directory,file))
        reader = reader.dropna()
        data.append(reader.iloc[:,1:5].values.astype('float32'))
        

In [10]:
sz = []
sz.append(len(data[0]))
dat= data[0]
for i in range(1,len(data)):
    sz.append(len(data[i]))
    dat = np.vstack((dat,data[i]))
    print(dat.shape, sz[i])

(96, 4) 24
(144, 4) 48
(168, 4) 24
(192, 4) 24
(240, 4) 48
(288, 4) 48
(360, 4) 72
(408, 4) 48
(432, 4) 24
(456, 4) 24
(480, 4) 24
(504, 4) 24
(600, 4) 96
(648, 4) 48
(672, 4) 24


In [0]:

from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))
dat[:] = sc.fit_transform(dat[:])

In [0]:
final_data = []
koto = 0
for i in sz:
    final_data.append(dat[koto: koto + i])
    koto += i
    

In [0]:
look_back = 7
data_x = []
data_y = []
for i in final_data:
    for j in range(len(i) - look_back):
        data_x.append(i[j: j + look_back])
        data_y.append(i[j + look_back])
    

In [0]:
data_x = np.array(data_x)
data_y = np.array(data_y)

In [0]:
x_train = data_x[0:500]
x_test = data_x[500:]
y_train = data_y[0:500]
y_test = data_y[500:]

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
model = Sequential()
model.add(LSTM(50, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dense(4))
model.compile(loss='mae', optimizer='adam')
# fit network
history = model.fit(x_train, y_train, epochs=50, batch_size=8, validation_data=(x_test, y_test), verbose=2, shuffle=False)

Using TensorFlow backend.






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 500 samples, validate on 60 samples
Epoch 1/50





 - 1s - loss: 0.2803 - val_loss: 0.1513
Epoch 2/50
 - 0s - loss: 0.1181 - val_loss: 0.1358
Epoch 3/50
 - 0s - loss: 0.0993 - val_loss: 0.1267
Epoch 4/50
 - 0s - loss: 0.0825 - val_loss: 0.1125
Epoch 5/50
 - 0s - loss: 0.0703 - val_loss: 0.0935
Epoch 6/50
 - 0s - loss: 0.0711 - val_loss: 0.0851
Epoch 7/50
 - 0s - loss: 0.0724 - val_loss: 0.0929
Epoch 8/50
 - 0s - loss: 0.0740 - val_loss: 0.0854
Epoch 9/50
 - 0s - loss: 0.0739 - val_loss: 0.0970
Epoch 10/50
 - 0s - loss: 0.0730 - val_loss: 0.0939
Epoch 11/50
 - 0s - loss: 0.0705 - val_loss: 0.0847
Epoch 12/50
 - 0s - loss: 0.0703 - val_loss: 0.0868
Epoch 13/50
 - 0s - loss: 0.0679 - val_loss: 0.0831
Epoch 14/50
 - 0s - loss: 0.0655 - val_loss: 0.0714
Epoch 15/50
 - 0s - loss: 0.0658 - val_loss: 0.0692
Epoch 16/50
 - 0s - loss: 0.0654 - val_loss: 0.0689
Epoch 17/50
 - 0s - loss: 

In [0]:
yhat = model.predict(x_test)

In [0]:
res = sc.inverse_transform(yhat)
ori = sc.inverse_transform(y_test)

In [19]:
for i in range(len(x_test)):
    print(res[i], ori[i])

[100.406364 127.31081   92.11021   52.34576 ] [ 98. 140.  91.  54.]
[100.02752  131.31993   91.67709   52.708332] [100. 137. 100.  55.]
[100.201645 150.70638   84.26031   54.461975] [100. 157.  81.  49.]
[100.17899 151.38977  81.51754  51.71851] [100. 149.  88.  53.]
[100.20788  147.73479   83.51148   52.796703] [100.       156.        68.        41.000004]
[100.20917  150.45288   76.27941   47.108654] [100. 165.  76.  42.]
[100.29156 154.3024   75.33917  44.5587 ] [100. 164.  68.  46.]
[100.38052  155.50528   73.45059   44.303448] [100. 148.  79.  52.]
[100.46072  149.07004   77.03934   48.016285] [100. 155.  74.  52.]
[100.459785 149.14716   76.99821   48.733498] [100. 156.  65.  44.]
[100.45213 150.54663  72.20945  45.74949] [100. 161.  77.  54.]
[100.46304  151.48848   74.93573   48.318977] [100. 146.  70.  51.]
[100.425995 146.92993   73.88365   49.241966] [100.       144.        68.        50.000004]
[100.40475 143.87111  72.41773  49.0819 ] [100. 149.  59.  39.]
[100.410484 145.